import { Navbar } from "@/components/NavBar";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <div>
          <button id='button'>Add background colour</button>
        </div>
        <Script id='myscript'>{`
          if (window) {
            window.document.getElementById('button').addEventListener('click', () => { document.body.style.backgroundColor = 'yellow' });
          }`}
        </Script>
      </body>
    </html>
  );
}
