import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <button id='button'>Add background colour</button>
        </div>
        <script>
          if (window) {
            window.document.getElementById('button').addEventListener('click', () => { document.body.style.backgroundColor = 'yellow' });
          }
        </script>
      </body>
    </html>
  );
}
